### ISSUE TITLE
keine aktuellen Energiedaten

### ISSUE THREAD

**Issue by menkej** [sebilm/ioBroker.myuplink#16]
**Describe the bug**  
Seit dem 1.2. werden keine aktuellen Energiedaten von myuplink geliefert? Woran mag es liegen? In der Anlage (Service-Menü)  werden aktuelle Werte angezeigt. Bin ich allein mit dem Problem? MyUplink Schuld, oder was im Adapter?

System: VVM500, F2120/12

**To Reproduce**  
Beispiel (aus dem Response json):

```
    {
        "category": "Heat meter",
        "parameterId": "44300",
        "parameterName": "Heating, includ­ing int. add. heat",
        "parameterUnit": "kWh",
        "writable": false,
        "timestamp": "2024-02-01T09:28:02+00:00",
        "value": 6367.5,
        "strVal": "6367.5kWh",
        "smartHomeCategories": [],
        "minValue": 0,
        "maxValue": 999999.9,
        "stepValue": 0.1,
        "enumValues": [],
        "scaleValue": "0.1",
        "zoneId": null
    },
```

Timestamp ist vom 1.2. - bei anderen Werten (z.B. Gradminuten) bekomme ich aktuelle Daten.

**Expected behavior**  
Akutelle Energiedaten in den Objekten

**Screenshots & Logfiles**  
Im Log steht nix.

**Versions:**  
 - Adapter version: 0.7.1
 - JS-Controller version: 5.0.17
 - Node version:  v16.20.2
 - Operating system: docker/unraid

**Additional context**

**Comment by menkej** [comment]
> Naja, wenn du schon im Response siehst, dass keine aktuellen Daten kommen, kann's ja nicht am Adapter liegen. MyUplink hat einen Support - bitte mal da nachfragen.

Mir ging es ja auch darum zu sehen, ob ich allein bin mit dem Problem. Bekommst du denn aktuelle Energiedaten? MyUplink Support habe ich gestern schon angeschrieben. Mal schauen, ob jemand zuckt.

**Comment by sebilm** [comment]
Das ist aber doch hier kein Forum für myuplink. Meine Wärmepumpe wurde noch nicht auf myuplink umgestellt, ich hab den Adapter nur schon mal vorsorglich geschrieben.
