### ISSUE TITLE
Danke, auf dich ist Verlass 

### ISSUE THREAD

**Issue by Wisley7** [sebilm/ioBroker.myuplink#17]
Genau, was ich wieder gebraucht habe. 
Wenn mir beim Betrieb was auffällt, melde ich mich. 
Ging bei mir auf Anhieb, trotz das ich zuerst die CallBack vergessen hatte. 
Datenpunkte ändern läuft bei mir auch. 
alles bis jetzt super.

**Comment by sebilm** [comment]
Vielen Dank, gern geschehen.
