### ISSUE TITLE
Readme.md contains multiple languages

### ISSUE THREAD

**Issue by mcm1957** [sebilm/ioBroker.myuplink#47]
Please remove the german version / all non english versions from Readme.md because Readme.md gets automatically translated and this will not work with multiple languages within Readme.md. You can add locatlized Readme pages in (docs/de and docs/en) like https://github.com/iobroker-community-adapters/ioBroker.pvforecast/tree/main/docs and add it to io-package (see https://github.com/iobroker-community-adapters/ioBroker.pvforecast/blob/main/io-package.json#L119-L122). Or you cann add a german README_de.md if you prefer.

**Comment by sebilm** [comment]
Done.
