### ISSUE TITLE
wrong temp value in BT1 when 99 degrees

### ISSUE THREAD

**Issue by FlorianSchulze** [sebilm/ioBroker.myuplink#53]
Hi Seb,

having a 95 degree outside air temperature (correct value!), correctly displayed in MyUplink, the Adapter tells 9.9 degrees. This temp value is used in some HPs if cooling is active to avoid compressor starts. Is this an overflow of a value? Any debug information I can provide?

{
"type": "state",
"common": {
"name": "avg. outdoor temp (BT1)",
"type": "number",
"role": "value",
"unit": "°C",
"read": true,
"write": false
},
"native": {},
"from": "system.adapter.nibeuplink.0",
"user": "system.user.admin",
"ts": 1722437503662,
"_id": "nibeuplink.0.UNIT_0.STATUS.AVG_OUTDOOR_TEMP_BT1",
"acl": {
"object": 1636,
"state": 1636,
"owner": "system.user.admin",
"ownerGroup": "system.group.administrator"
}
}

Cheers,
Florian

**Comment by sebilm** [comment]
But your JSON says: nibeuplink... You confuse me ;-)

**Comment by FlorianSchulze** [comment]
sometimes the problem is 40 cm in front of the device. this is a migrated pump and all values in myuplink are correct. however, the old adapter still runs and delivers "online" and bullshit values. I did not reccognize i am dealing with the wrong adapter. thanks for pointing out!
