### ISSUE TITLE
Response "modified" wird als Error angezeigt.

### ISSUE THREAD

**Issue by m-s-b** [sebilm/ioBroker.myuplink#60]
**Describe the bug**  
Wenn über den Set-Datenpunkt eine ID gesteuert wird kommt mittlerweile von Nibe ein Response modified.
Das wir vom Adapter als Error behandelt.
**To Reproduce**  
1. state myuplink.0.Heizung.Home.setData changed: { "47260": "1" } (ack = false)
2. SetData: "{ "47260": "1" }" Result: "{ "47260": "modified" }

**Expected behavior**  
Modified steht hier nur für die positive Rückmeldung, sollte daher nicht als "Error" im Log auftauchen.
**Screenshots & Logfiles**  
`myuplink.0 2024-09-10 09:14:08.594	error	SetData: "{ "47260": "1" }" Result: "{ "47260": "modified" }"
myuplink.0 2024-09-10 09:14:08.593	debug	Response from PATCH /v2/devices/emmy-r-DEVICE-ID/points (lang: de): { "47260": "modified" }
myuplink.0 2024-09-10 09:14:05.582	debug	PATCH /v2/devices/emmy-r-DEVICE-ID/points (lang: de)
myuplink.0 2024-09-10 09:14:05.582	debug	Is token expired: false
myuplink.0 2024-09-10 09:14:05.582	debug	Has access token: true
myuplink.0 2024-09-10 09:14:05.581	debug	Get access token
myuplink.0 2024-09-10 09:14:05.580	debug	state myuplink.0.Heizung.Home.setData changed: { "47260": "1" } (ack = false)`

**Versions:**  
 - Adapter version: 0.8.1
 - JS-Controller version: 6.0.11
 - Node version: 20.17.0
 - Operating system: Debian 12

**Additional context**  
Auf der Heizung läuft aktuell die Firmware Version: 9699R5, tippe aber eher auf Änderung der API.

**Comment by sebilm** [comment]
Ich glaube, da wurde beim Response eine Zwischenklasse weg gelassen. Nicht schön, wenn sich die API einfach ändert.

**Comment by m-s-b** [comment]
Gerne! 
Kein Stress deswegen, läuft ja sonst alles wie es soll.

**Comment by sebilm** [comment]
Sollte mit Version 0.8.2 gefixt sein. Bitte mal Rückmeldung geben.

**Comment by m-s-b** [comment]
Vielen Dank, läuft bei mir wieder ohne Errors !
